### ISSUE TITLE
v2.0 Milestones

### ISSUE THREAD

**Issue by Reoseah** [Reoseah/Reinforcement#2]
Implement different outdated IC2 addons for 1.10. Not simple update, things could be changed radically. Likely no original code or assets would be used.

- [ ] Rename addon
- [ ] Implement DeFence addon things
- [ ] Implement CatWalks mod things (in simple form, without advanced configuration)
- [ ] Implement Advanced Machines addon things
- [ ] Add Prismarine-superconductor, wire from it
- [ ] Add advanced passive generator similar to Ultimate Solar Panels addon
- [ ] Implement GraviSuit addon things

**Comment by Reoseah** [comment]
- [ ] Creeper deterrent machine
